export const todoTypes = {
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  MARK_COMPLETE: "MARK_COMPLETE",
  UNDO_COMPLETE: "UNDO_COMPLETE",
  GET_ACTIVE: "GET_ACTIVE",
  GET_COMPLETED: "GET_COMPLETED",
  GET_ALL: "GET_ALL",
  CLEAR_COMPLETED: "CLEAR_COMPLETED",
  SET_THEME: "SET_THEME",
};
